name: CI PRs

on:
  pull_request:
    branches:
      - 'main'
      - '0.x'
    paths-ignore:
      - '.github/**'

jobs:
  build_and_verify:
    name: Build and Verify
    if: ${{ github.repository == 'spring-projects/spring-grpc' }}
    strategy:
      matrix:
        include:
          - javaVersion: 25
            distribution: 'liberica'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.javaVersion }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: ${{ matrix.distribution }}
          cache: maven
      - name: Build, test, and run samples (Java ${{ matrix.javaVersion }} ${{ matrix.distribution }})
        run: |
          ./mvnw -B clean install
      - name: Upload Build Reports (Java ${{ matrix.javaVersion }} ${{ matrix.distribution }})
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-java-${{ matrix.javaVersion }}-${{ matrix.distribution }}
          path: '*/target/surefire-reports/*.*'
          retention-days: 3
